### ISSUE TITLE
Make errors more informative.

### ISSUE THREAD

**Issue by j3pic** [phoe/safe-read#2]
I tried using `safe-read` to read in an ASDF file, but it failed with a `SAFE-READ::MALFORMED-INPUT` error. The only way I could possibly find out *why* it failed with that error was to debug the SAFE-READ library. This was made difficult by the use of this pattern:

```common-lisp
(handler-case
   (code that might fail)
  (malformed-input (e)
      (setf (buffer-of stream) "")
      (signal e)))
```

The result of doing that instead of using HANDLER-BIND is that the debugger doesn't
show the call to the `signal-malformed-input` function on the stack. If that was on the stack it would be possible to use the debugger to see which character caused the error. In my case it was `:`.

**Comment by phoe** [comment]
Oh goodness, how young I was when I wrote this code! Let me fix it.
